---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: nginxapp
  namespace: fluxcd-deploy
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/mkamran1411/fluxcd-deploy
