apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginxappkust
  namespace: fluxcd-deploy
spec:
  interval: 30s
  path: ./deploy
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: nginxapp
